# Generated by Django 4.2.5 on 2023-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryoptions",
            name="delivery_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "The price must be between 0 and 999.99."}
                },
                help_text="Maximum 999.99",
                max_digits=5,
                verbose_name="delivery price",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryoptions",
            name="delivery_timeframe",
            field=models.CharField(
                help_text="Required", max_length=255, verbose_name="delivery timeframe"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryoptions",
            name="delivery_window",
            field=models.CharField(
                help_text="Required", max_length=255, verbose_name="delivery window"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryoptions",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Required", verbose_name="list order"
            ),
        ),
    ]
